import type { Metadata } from "next";
import { Anybody, Ubuntu, Roboto, Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { ConsultUs } from "./components";
import { Header } from "./components/Header";

const anybody = Anybody({
  subsets: ["latin"],
  variable: "--font-anybody",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-roboto",
  display: "swap",
});

const ubuntu = Ubuntu({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-ubuntu",
  display: "swap",
});

export const metadata: Metadata = {
  title: "A-Z New Age Tutors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anybody.variable} ${ubuntu.variable} ${roboto.variable} ${inter.variable} ${ubuntu.className} text-[24px] leading-[28.8px] max-md:w-screen max-md:text-[14px] max-md:leading-[21px]`}
      >
        <Header />
        <main className="mx-[38px] ">
          {children}
          <ConsultUs />
        </main>
        <footer>
          <section className="bg-black pt-[97px] max-md:pt-[33px] md:pb-[70px] pb-[33px] text-white px-[40px]">
            <div className="flex flex-wrap md:justify-between max-w-[1071px] m-auto gap-y-[40px] justify-start max-md:gap-x-[30px]">
              <div className="flex flex-col max-w-[431px]">
                <h4 className="mb-[16px] text-white">
                  Sign-up for our newsletter
                </h4>
                <p className="pb-[52px] text-gray">
                  Get exclusive educational{" "}
                  <span className="text-white">tips and updates</span> straight
                  to your mailbox.
                </p>
                <div className="pl-[30px] h-[55.54px] flex bg-white self-start">
                  <Image src="/email.svg" alt="email" width={24} height={24} />
                  <input
                    type="email"
                    placeholder="Email address"
                    className="newsletter-email text-black tracking-[0.12em] w-full placeholder:text-black2 max-md:text-[16px] ml-[12px] pl-[12px]"
                  />
                  <div className="bg-primary flex justify-center items-center max-w-[79px] min-w-[64px]">
                    <Image
                      src="/arrow.svg"
                      alt="send"
                      width={18.75}
                      height={15.75}
                    />
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-[28.8px] text-gray">
                <a href="" className="font-bold text-white">
                  About
                </a>
                <a href="">Our Team</a>
                <a href="">Blog</a>
                <a href="">Our services</a>
              </div>
              <div className="flex flex-col gap-[28.8px] text-gray">
                <a href="" className="font-bold text-white">
                  Company
                </a>
                <a href="">Career</a>
                <a href="">Our team</a>
                <a href="">Contact</a>
              </div>
            </div>
          </section>
          <section className="pt-[23.46px] pb-[22.54px] flex flex-col items-center gap-[7px]">
            <div className="flex gap-[28px]">
              <Image
                src="/facebook.svg"
                alt="facebook"
                width={40}
                height={40}
              />
              <Image src="/x.svg" alt="x" width={40} height={40} />
              <Image
                src="/instagram.svg"
                alt="instagram"
                width={40}
                height={40}
              />
            </div>
            <div className="flex gap-[4.5px] copyright items-center tracking-[0.12em]">
              <Image
                src="/copyright.svg"
                alt="copyright"
                width={20}
                height={20}
              />
              2023 | A-Z New Age Tutors
            </div>
          </section>
        </footer>
      </body>
    </html>
  );
}
